//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_Language.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnglishTerm
    {
        public EnglishTerm()
        {
            this.TranslatedTerms = new HashSet<TranslatedTerm>();
        }
    
        public int EnglishTermID { get; set; }
        public string Term { get; set; }
        public string BeforeOrAfter { get; set; }
    
        public virtual ICollection<TranslatedTerm> TranslatedTerms { get; set; }
    }
}
