//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_Language.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranslatedTerm
    {
        public int TranslationID { get; set; }
        public int LanguageID { get; set; }
        public int EnglishTermID { get; set; }
        public string TermTranslated { get; set; }
    
        public virtual EnglishTerm EnglishTerm { get; set; }
        public virtual Language Language { get; set; }
    }
}
